---

- name: Install lychee Apache configuration
  template:
    src: "etc/apache2/sites-available/lychee.conf.j2"
    dest: "/etc/apache2/sites-available/lychee.conf"

- name: Enable Lychee Apache site
  shell: a2ensite lychee

