---

- name: Create Lychee user account
  user:
    name: "{{ lychee_user }}"
    shell: "/bin/bash"
    state: present
    ssh_key_type: rsa
    createhome: yes
    home: "{{ lychee_home }}"

- name: Clone Lychee repository
  become: yes
  become_user: "{{ lychee_user }}"
  become_method: sudo
  git:
    clone: yes
    repo: "{{ lychee_repository }}"
    dest: "{{ lychee_document_root }}"
    version: "{{ lychee_version }}"

- name: "Setup Apache/Lychee permissions"
  acl:
    name: "{{ lychee_document_root }}/{{ item }}"
    entity: www-data
    permissions: rwx
    recursive: yes
    state: present
    etype: user
  with_items:
    - data
    - uploads

- name: Configure Lychee
  template:
    src: "home/lychee/lychee/data/config.php.j2"
    dest: "{{ lychee_document_root }}/data/config.php"

- name: Lock Lychee user account
  user: name="{{ lychee_user }}" shell="/bin/false"

