---
#
# Main configuration file for setting up a photo
# server running Lychee
#

- include: "apache.yml"
  become: yes
  become_user: root
- include: "install.yml"
  become: yes
  become_user: root
- include: "database.yml"
  become: yes
  become_user: root

- name: Restart Apache
  become: yes
  become_user: root
  service: name=apache2 state="{{ item }}"
  with_items:
    - stopped
    - started
