---
#
# Main configuration file for setting up a photo
# server running Lychee
#

- include: "apache.yml"
  sudo: yes
- include: "install.yml"
  sudo: yes
- include: "database.yml"
  sudo: yes

- name: Restart Apache
  sudo: yes
  service: name=apache2 state="{{ item }}"
  with_items:
    - stopped
    - started
